version: '3.9'

services:
  simple-user-service:
    restart: always
    build:
      context: .
    env_file:
      - .env
    ports:
      - '${PORT}:${PORT}'
  database:
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      PGADMIN_DEFAULT_EMAIL: some@mail.com
    volumes:
      - ./data/db-data/:/var/lib/postgresql/data/
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
